### ISSUE TITLE
Loop Points Not Working

### ISSUE THREAD

**Issue by PranchaD** [GM82Project/gm82snd#1]
When I try to make a loop points it doesn't work.
Create:
bgm_play(bgm_test, 1, 1, true, 81000, 1816000, 44100);
Begin Step:
/// Loop music using samples.

   if(bgm_sample_loop == true)
   {
      if(bgm_handle != noone)
      {
         if(sound_get_length(bgm_handle) >= bgm_sample_end/bgm_sample_rate)
         {
            sound_set_loop(bgm_handle, bgm_sample_start/bgm_sample_rate, bgm_sample_end/bgm_sample_rate);
         }
      } 
   }
Bgm Script:
 // Check if there's music already playing.
    if(SFX.bgm_handle != noone)
    {
       if(sound_isplaying(SFX.bgm_handle))
       {
          sound_stop(SFX.bgm_handle);
       }
       SFX.bgm_handle = noone;
    }
    
 // Set music handle and other things.
    SFX.bgm_handle       = sound_loop_single(SFX.argument0);
                           sound_volume (SFX.bgm_handle, argument1);
                           sound_pitch (SFX.bgm_handle, argument2);
    SFX.bgm_sample_loop  = argument3;
    SFX.bgm_sample_start = argument4;
    SFX.bgm_sample_end   = argument5;
    SFX.bgm_sample_rate  = argument6;

**Comment by omicronrex** [comment]
That's not how you do that - you're supposed to set the loop point in the sound index with a 0..1 value, once, after loading the sound. Then, looping the sound will automatically respect the loop points you have set.

For example, a loop between 00:02.500 and 01:25:300:

```
length=sound_get_length(bgm_test)
intro=2.5/length
loop=85.3/length

sound_set_loop(bgm_test,intro,loop)
sound_loop_single(bgm_test)
```

**Comment by PranchaD** [comment]
oops, I didn't said how the script, my bad, but what it will do is bgm_sample_rate divide bgm_sample_start or bgm_sample_end so that's makes 0.0 value, example 81000/44100 = 1.84, still tried to do what you said and nothing yet for some reason.

**Comment by omicronrex** [comment]
It's not measured in samples. It's measured in seconds, so you're suposed to divide by length.

**Comment by PranchaD** [comment]
like I said I made what you said
sound_loop_single(bgm_test);
length  = sound_get_length(bgm_test);
bgm_sample_start = 1.84/length;
bgm_sample_end  = 41.1/length;
sound_set_loop(bgm_test, bgm_sample_start, bgm_sample_end);
(I need to put sound_loop_single before or else I get a error)

**Comment by omicronrex** [comment]
preload the sound, then set loop, then play it.

**Comment by PranchaD** [comment]
oh now it worked, thanks a lot.
